# Generated by Django 5.2.8 on 2025-12-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_add_vendor_fields_and_update_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendoranalytics',
            options={'ordering': ['-date', 'vendor'], 'verbose_name': 'Vendor Analytics', 'verbose_name_plural': 'Vendor Analytics'},
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='avg_order_value',
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='sales_trend',
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='vendoranalytics',
            name='total_views',
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='active_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='date',
            field=models.DateField(db_index=True, default='2025-12-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='low_stock_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='out_of_stock_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='pending_bulk_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoranalytics',
            name='weekly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendoranalytics',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='store.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='vendoranalytics',
            unique_together={('vendor', 'date')},
        ),
    ]
