# Generated by Django 5.2.8 on 2025-12-08 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_update_vendor_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoranalytics',
            old_name='top_products',
            new_name='top_selling_products',
        ),
        migrations.AddIndex(
            model_name='bulkorder',
            index=models.Index(fields=['user', 'status'], name='idx_bulkorder_user_status'),
        ),
        migrations.AddIndex(
            model_name='bulkorder',
            index=models.Index(fields=['vendor', 'status'], name='idx_bulkorder_vendor_status'),
        ),
        migrations.AddIndex(
            model_name='buyerinquiry',
            index=models.Index(fields=['buyer', 'status'], name='idx_inquiry_buyer_status'),
        ),
        migrations.AddIndex(
            model_name='buyerinquiry',
            index=models.Index(fields=['vendor', 'status'], name='idx_inquiry_vendor_status'),
        ),
        migrations.AddIndex(
            model_name='buyerinquiry',
            index=models.Index(fields=['is_urgent', 'created_at'], name='idx_inquiry_urgent_date'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_category_slug'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='idx_coupon_active_validity'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='idx_flashsale_active_time'),
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['slug'], name='idx_flashsale_slug'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', 'created_at'], name='idx_invlog_product_date'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['action'], name='idx_invlog_action'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='idx_message_sender_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='idx_message_receiver_read'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='idx_order_user_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'paid'], name='idx_order_status_paid'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='idx_order_email'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='idx_orderitem_order_product'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['vendor', 'vendor_paid'], name='idx_orderitem_vendor_paid'),
        ),
        migrations.AddIndex(
            model_name='premiumlisting',
            index=models.Index(fields=['position', 'is_active', 'start_date', 'end_date'], name='idx_premium_position_active'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city', 'state'], name='idx_profile_location'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_kyc_verified'], name='idx_profile_kyc'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='idx_review_product_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='idx_review_user'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase'], name='idx_review_verified'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['buyer', 'status'], name='idx_rfq_buyer_status'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'is_public'], name='idx_rfq_status_public'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['category'], name='idx_rfq_category'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active', 'is_verified'], name='idx_vendor_active_verified'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['rating'], name='idx_vendor_rating'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['city'], name='idx_vendor_city'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'added_at'], name='idx_wishlist_user_date'),
        ),
    ]
