# Generated by Django 5.2.8 on 2025-12-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_add_all_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('hindi_name', models.CharField(blank=True, help_text='Name in Hindi', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for the crop', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('all', 'All Seasons')], default='all', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_popular', 'order'], name='idx_crop_popular_order'), models.Index(fields=['season'], name='idx_crop_season')],
            },
        ),
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(default='Deal of the Day', max_length=255)),
                ('discount_percentage', models.PositiveIntegerField(default=20)),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='23:59:59')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='deal_of_day', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Deals of the Day',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('hindi_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True, help_text='Visible symptoms of the disease')),
                ('prevention_tips', models.TextField(blank=True)),
                ('is_common', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_crops', models.ManyToManyField(blank=True, related_name='diseases', to='store.crop')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocationPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('cart_add_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(default=0.0, help_text='Calculated score for ranking')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_popularity', to='store.product')),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('reset', 'Password Reset'), ('verify', 'Phone Verification')], default='login', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_verified'], name='idx_otp_phone_purpose')],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price_at_creation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCropMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness_rating', models.PositiveIntegerField(default=5, help_text='Rating 1-10 for how effective this product is for this crop')),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='store.crop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_mappings', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiseaseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness_rating', models.PositiveIntegerField(default=5, help_text='Rating 1-10 for how effective this product is against this disease')),
                ('dosage_info', models.TextField(blank=True, help_text='Specific dosage for this disease')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='store.disease')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_mappings', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='e.g., 500ml, 1kg, 5L', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_options', to='store.product')),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_spent', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('user_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.usercoin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this price tier')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_pricing_tiers', to='store.product')),
            ],
            options={
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['is_common', 'order'], name='idx_disease_common_order'),
        ),
        migrations.AddIndex(
            model_name='locationpopularity',
            index=models.Index(fields=['city', 'popularity_score'], name='idx_locpop_city_score'),
        ),
        migrations.AddIndex(
            model_name='locationpopularity',
            index=models.Index(fields=['state', 'popularity_score'], name='idx_locpop_state_score'),
        ),
        migrations.AlterUniqueTogether(
            name='locationpopularity',
            unique_together={('product', 'city')},
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['product', 'is_active', 'target_price'], name='idx_pricealert_product'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'is_active'], name='idx_pricealert_user'),
        ),
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productcropmapping',
            unique_together={('product', 'crop')},
        ),
        migrations.AlterUniqueTogether(
            name='productdiseasemapping',
            unique_together={('product', 'disease')},
        ),
        migrations.AddIndex(
            model_name='productpackingoption',
            index=models.Index(fields=['product', 'is_default'], name='idx_packing_product_default'),
        ),
    ]
