# Generated by Django 5.2.8 on 2025-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_agrim_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_instant_pack',
            field=models.BooleanField(default=False, help_text='Ready for instant shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_score',
            field=models.IntegerField(default=0, help_text='Score for trending ranking'),
        ),
    ]
