# Generated by Django 5.2.8 on 2025-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_agrim_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_min_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Minimum quantity for bulk price'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for bulk orders', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('distributor', 'Distributor'), ('farmer', 'Farmer')], default='retailer', max_length=20),
        ),
    ]
