# Generated by Django 5.2.8 on 2025-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_trackingconfiguration_useranalyticsapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=True, help_text='Whether the review has been approved by moderation'),
        ),
        migrations.AddField(
            model_name='review',
            name='vendor_response',
            field=models.TextField(blank=True, help_text="Vendor's response to this review"),
        ),
        migrations.AddField(
            model_name='review',
            name='vendor_response_at',
            field=models.DateTimeField(blank=True, help_text='When the vendor responded', null=True),
        ),
    ]
