# Generated by Django 5.2.8 on 2025-12-12 07:25

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_review_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='Last time user was notified about this item', null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notify_on_restock',
            field=models.BooleanField(default=False, help_text='Notify when product is back in stock'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='notify_on_sale',
            field=models.BooleanField(default=False, help_text='Notify when product goes on sale'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price_when_added',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product price when added to wishlist', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Notify when price drops to this value', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['notify_on_sale'], name='idx_wishlist_notify_sale'),
        ),
    ]
