# Generated by Django 6.0.1 on 2026-01-11 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50, unique=True)),
                (
                    "retention_period",
                    models.PositiveIntegerField(
                        help_text="Number of units to retain data"
                    ),
                ),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="months",
                        max_length=20,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("operation_type", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("previous_state", models.JSONField(blank=True, null=True)),
                ("new_state", models.JSONField(blank=True, null=True)),
                ("changed_fields", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
                "indexes": [
                    models.Index(
                        fields=["model_name", "timestamp"],
                        name="store_datam_model_n_d7113b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="store_datam_user_id_442954_idx",
                    ),
                    models.Index(
                        fields=["operation_type"], name="store_datam_operati_959cf1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Tracker",
                "verbose_name_plural": "Session Trackers",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="store_sessi_user_id_7e5bfb_idx",
                    ),
                    models.Index(
                        fields=["login_timestamp"],
                        name="store_sessi_login_t_ab0383_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(blank=True, max_length=255)),
                ("is_successful", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
                "indexes": [
                    models.Index(
                        fields=["access_type", "access_timestamp"],
                        name="store_syste_access__8dab9a_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "access_timestamp"],
                        name="store_syste_ip_addr_b3fc9a_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="store_syste_risk_le_9c1e95_idx"
                    ),
                ],
            },
        ),
    ]
