# Generated by Django 5.2.10 on 2026-01-10 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100, unique=True)),
                (
                    "origin_location",
                    models.CharField(
                        help_text="Farm or facility location", max_length=255
                    ),
                ),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "certification",
                    models.CharField(
                        blank=True, help_text="e.g. Organic, ISO", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "qr_code_data",
                    models.TextField(
                        blank=True, help_text="Data for QR code generation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JourneyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("harvest", "Harvested"),
                            ("processing", "Processing"),
                            ("packaging", "Packaging"),
                            ("shipping", "Shipping"),
                            ("transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("retail", "Retail Store"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "handler",
                    models.CharField(
                        blank=True,
                        help_text="Person/Company handling this stage",
                        max_length=100,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Storage temp in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="supply_chain/"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey",
                        to="store.productbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.TextField(blank=True)),
                ("banned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=1)),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="store_banne_ip_addr_1d0be2_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="store_banne_expires_e8d78f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["batch_id"], name="store_produ_batch_i_f46e49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["product", "created_at"], name="store_produ_product_420a2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeypoint",
            index=models.Index(
                fields=["batch", "timestamp"], name="store_journ_batch_i_dc8999_idx"
            ),
        ),
    ]
