# Generated by Django 5.2.10 on 2026-01-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="established_date",
            field=models.DateField(
                blank=True, help_text="Date when vendor started business", null=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
