# Generated by Django 5.2.10 on 2026-01-26 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("file_operations", "File Operations"),
                            ("user_actions", "User Actions"),
                            ("system_access", "System Access"),
                            ("data_modifications", "Data Modifications"),
                            ("sessions", "Sessions"),
                            ("performance_metrics", "Performance Metrics"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "retention_period",
                    models.PositiveIntegerField(
                        help_text="Number of units to retain data"
                    ),
                ),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        max_length=20,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("logout_timestamp", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(max_length=255)),
                ("is_successful", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-access_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["access_type", "access_timestamp"],
                        name="store_syste_access__8dab9a_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="store_syste_ip_addr_18019d_idx"
                    ),
                ],
            },
        ),
    ]
