# Generated by Django 5.2.10 on 2026-01-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50, unique=True)),
                ("retention_period", models.PositiveIntegerField(default=90)),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("farming_tips", "Farming Tips"),
                            ("crop_issues", "Crop Issues"),
                            ("market_trends", "Market Trends"),
                            ("general", "General Discussion"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="forum/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="store.forumpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
                "indexes": [
                    models.Index(
                        fields=["model_name", "timestamp"],
                        name="store_datam_model_n_d7113b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="store_datam_user_id_442954_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per quintal", max_digits=10
                    ),
                ),
                ("date", models.DateField()),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("stable", "Stable")],
                        default="stable",
                        max_length=20,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="store.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "crop"],
                "unique_together": {("crop", "market_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Tracker",
                "verbose_name_plural": "Session Trackers",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="store_sessi_user_id_7e5bfb_idx",
                    ),
                    models.Index(
                        fields=["last_activity"], name="store_sessi_last_ac_6fe182_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(blank=True, max_length=255)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
                "indexes": [
                    models.Index(
                        fields=["access_type", "access_timestamp"],
                        name="store_syste_access__8dab9a_idx",
                    ),
                    models.Index(
                        fields=["user", "access_timestamp"],
                        name="store_syste_user_id_3c4b61_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "access_timestamp"],
                        name="store_syste_ip_addr_b3fc9a_idx",
                    ),
                ],
            },
        ),
    ]
