# Generated by Django 5.2.10 on 2026-01-25 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50, unique=True)),
                ("retention_period", models.PositiveIntegerField(default=90)),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        max_length=20,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
            },
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trackingalert",
            name="triggered_by",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="TrackingExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=50)),
                ("format", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(default=0)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export",
                "verbose_name_plural": "Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                ("object_repr", models.CharField(max_length=255)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
                "indexes": [
                    models.Index(
                        fields=["operation_type", "timestamp"],
                        name="store_datam_operati_3f58fc_idx",
                    ),
                    models.Index(
                        fields=["model_name", "timestamp"],
                        name="store_datam_model_n_d7113b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="store_datam_user_id_442954_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("login_method", models.CharField(default="password", max_length=50)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Tracker",
                "verbose_name_plural": "Session Trackers",
                "indexes": [
                    models.Index(
                        fields=["user", "login_timestamp"],
                        name="store_sessi_user_id_a6837a_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="store_sessi_is_acti_a670ef_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="store_sessi_session_70fe85_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("is_successful", models.BooleanField(default=True)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                ("resource_accessed", models.CharField(max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
                "indexes": [
                    models.Index(
                        fields=["access_type", "access_timestamp"],
                        name="store_syste_access__8dab9a_idx",
                    ),
                    models.Index(
                        fields=["user", "access_timestamp"],
                        name="store_syste_user_id_3c4b61_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="store_syste_risk_le_9c1e95_idx"
                    ),
                ],
            },
        ),
    ]
