# Generated by Django 6.0.1 on 2026-01-08 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.TextField()),
                ("banned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Banned IP",
                "verbose_name_plural": "Banned IPs",
            },
        ),
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50, unique=True)),
                ("retention_period", models.PositiveIntegerField(default=90)),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                ("quantity", models.PositiveIntegerField()),
                ("manufacturing_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("current_location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="batch_qr/"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.vendor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Batch",
                "verbose_name_plural": "Product Batches",
            },
        ),
        migrations.CreateModel(
            name="JourneyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("manufactured", "Manufactured"),
                            ("in_transit", "In Transit"),
                            ("warehouse", "At Warehouse"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=50,
                    ),
                ),
                ("handler_name", models.CharField(blank=True, max_length=100)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey",
                        to="store.productbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Point",
                "verbose_name_plural": "Journey Points",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                ("object_repr", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="store_datam_timesta_56d9d1_idx"
                    ),
                    models.Index(
                        fields=["operation_type"], name="store_datam_operati_959cf1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Tracker",
                "verbose_name_plural": "Session Trackers",
                "indexes": [
                    models.Index(
                        fields=["login_timestamp"],
                        name="store_sessi_login_t_ab0383_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="store_sessi_is_acti_a670ef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(blank=True, max_length=255)),
                ("is_successful", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
                "indexes": [
                    models.Index(
                        fields=["access_timestamp"],
                        name="store_syste_access__52768f_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="store_syste_risk_le_9c1e95_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="store_syste_ip_addr_18019d_idx"
                    ),
                ],
            },
        ),
    ]
