# Generated by Django 5.2.10 on 2026-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranalyticsapikey",
            name="secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
