# Generated by Django 6.0 on 2026-01-06 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        help_text="Unique Batch ID / QR Code",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("harvested", "Harvested"),
                            ("processing", "Processing"),
                            ("packaged", "Packaged"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("warehouse", "At Warehouse"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "handler",
                    models.CharField(
                        help_text="Name of person/entity handling this step",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "coordinates",
                    models.CharField(blank=True, help_text="Lat,Long", max_length=100),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey",
                        to="store.productbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RestockRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_stockout_date", models.DateField()),
                ("recommended_quantity", models.PositiveIntegerField()),
                (
                    "confidence_score",
                    models.FloatField(help_text="0.0 to 1.0 confidence"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_actioned", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_recommendations",
                        to="store.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_recommendations",
                        to="store.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["predicted_stockout_date"],
            },
        ),
        migrations.CreateModel(
            name="BannedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.CharField(max_length=255)),
                ("banned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banned_until",
                    models.DateTimeField(
                        blank=True, help_text="Null means permanent ban", null=True
                    ),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-banned_at"],
                "indexes": [models.Index(fields=["ip_address"], name="idx_banned_ip")],
            },
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(fields=["batch_id"], name="idx_batch_id"),
        ),
        migrations.AddIndex(
            model_name="journeypoint",
            index=models.Index(
                fields=["batch", "timestamp"], name="idx_journey_batch_time"
            ),
        ),
        migrations.AddIndex(
            model_name="restockrecommendation",
            index=models.Index(
                fields=["vendor", "is_actioned"], name="idx_restock_vendor_action"
            ),
        ),
    ]
