# Generated by Django 6.0.1 on 2026-01-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("file_operations", "File Operations"),
                            ("user_actions", "User Actions"),
                            ("system_access", "System Access"),
                            ("data_modifications", "Data Modifications"),
                            ("sessions", "Sessions"),
                            ("performance_metrics", "Performance Metrics"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "retention_period",
                    models.PositiveIntegerField(
                        help_text="Number of units to retain data"
                    ),
                ),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        max_length=20,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
            },
        ),
        migrations.AlterField(
            model_name="useractiontracker",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("page_view", "Page View"),
                    ("button_click", "Button Click"),
                    ("form_submit", "Form Submit"),
                    ("search", "Search Query"),
                    ("filter_apply", "Filter Applied"),
                    ("sort_apply", "Sort Applied"),
                    ("download", "Download"),
                    ("upload", "Upload"),
                    ("purchase", "Purchase"),
                    ("cart_add", "Add to Cart"),
                    ("cart_remove", "Remove from Cart"),
                    ("wishlist_add", "Add to Wishlist"),
                    ("wishlist_remove", "Remove from Wishlist"),
                    ("review_submit", "Review Submitted"),
                    ("profile_update", "Profile Updated"),
                    ("password_change", "Password Changed"),
                    ("email_change", "Email Changed"),
                    ("custom_action", "Custom Action"),
                    ("data_modification", "Data Modification"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TrackingExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=50)),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV")], max_length=10
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("record_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Export",
                "verbose_name_plural": "Data Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("is_sensitive", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
                "indexes": [
                    models.Index(
                        fields=["operation_type", "timestamp"],
                        name="store_datam_operati_3f58fc_idx",
                    ),
                    models.Index(
                        fields=["model_name", "timestamp"],
                        name="store_datam_model_n_d7113b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="store_datam_user_id_442954_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("login_method", models.CharField(default="password", max_length=50)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "login_timestamp"],
                        name="store_sessi_user_id_a6837a_idx",
                    ),
                    models.Index(
                        fields=["is_active", "last_activity"],
                        name="store_sessi_is_acti_15a901_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="store_sessi_session_70fe85_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("login_attempt", "Login Attempt"),
                            ("login_success", "Login Success"),
                            ("login_failure", "Login Failure"),
                            ("logout", "Logout"),
                            ("api_access", "API Access"),
                            ("admin_access", "Admin Panel Access"),
                            ("file_access", "File Access"),
                            ("database_access", "Database Access"),
                            ("page_access", "Page Access"),
                            ("sql_injection", "SQL Injection Attempt"),
                            ("xss_attempt", "XSS Attempt"),
                            ("csrf_violation", "CSRF Violation"),
                            ("brute_force", "Brute Force Attempt"),
                            ("path_traversal", "Path Traversal Attempt"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("error", "System Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(blank=True, max_length=255)),
                ("is_successful", models.BooleanField(default=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
                "indexes": [
                    models.Index(
                        fields=["access_type", "access_timestamp"],
                        name="store_syste_access__8dab9a_idx",
                    ),
                    models.Index(
                        fields=["user", "access_timestamp"],
                        name="store_syste_user_id_3c4b61_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "access_timestamp"],
                        name="store_syste_ip_addr_b3fc9a_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "access_timestamp"],
                        name="store_syste_risk_le_fa58d5_idx",
                    ),
                ],
            },
        ),
    ]
