# Generated by Django 5.2.10 on 2026-01-14 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("file_operations", "File Operations"),
                            ("user_actions", "User Actions"),
                            ("system_access", "System Access"),
                            ("data_modifications", "Data Modifications"),
                            ("sessions", "Sessions"),
                            ("performance_metrics", "Performance Metrics"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "retention_period",
                    models.PositiveIntegerField(
                        default=90, help_text="Retention period value"
                    ),
                ),
                (
                    "retention_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        default="days",
                        max_length=20,
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
                "indexes": [
                    models.Index(
                        fields=["model_name", "timestamp"],
                        name="store_datam_model_n_d7113b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="store_datam_user_id_442954_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Tracker",
                "verbose_name_plural": "Session Trackers",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="store_sessi_user_id_7e5bfb_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="store_sessi_session_38fe06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("failed_login", "Failed Login"),
                            ("api_access", "API Access"),
                            ("admin_access", "Admin Access"),
                            ("file_access", "File Access"),
                            ("db_access", "Database Access"),
                            ("sql_injection", "SQL Injection Attempt"),
                            ("xss_attempt", "XSS Attempt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(blank=True, max_length=255)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
                "indexes": [
                    models.Index(
                        fields=["access_type", "access_timestamp"],
                        name="store_syste_access__8dab9a_idx",
                    ),
                    models.Index(
                        fields=["user", "access_timestamp"],
                        name="store_syste_user_id_3c4b61_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "access_timestamp"],
                        name="store_syste_ip_addr_b3fc9a_idx",
                    ),
                ],
            },
        ),
    ]
