# Generated by Django 6.0.1 on 2026-01-13 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        help_text="Unique Batch ID / Lot Number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("production_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("origin_location", models.CharField(max_length=255)),
                ("current_location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("production", "In Production"),
                            ("quality_check", "Quality Check"),
                            ("packaging", "Packaging"),
                            ("transit", "In Transit"),
                            ("warehouse", "In Warehouse"),
                            ("retail", "At Retailer"),
                            ("sold", "Sold"),
                            ("consumed", "Consumed"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True, help_text="Immutable ledger hash", max_length=100
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="batch_qr/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.product",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="store.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        help_text="Status at this point (e.g., 'Arrived', 'Departed')",
                        max_length=50,
                    ),
                ),
                (
                    "handler",
                    models.CharField(
                        blank=True,
                        help_text="Person or company handling the batch",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "coordinates",
                    models.CharField(blank=True, help_text="Lat,Lng", max_length=50),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_points",
                        to="store.productbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(fields=["batch_id"], name="idx_batch_id"),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["product", "status"], name="idx_batch_product_status"
            ),
        ),
        migrations.AddIndex(
            model_name="journeypoint",
            index=models.Index(
                fields=["batch", "timestamp"], name="idx_journey_batch_time"
            ),
        ),
    ]
