# Generated by Django 6.0 on 2026-01-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataModificationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                ("object_repr", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Data Modification",
                "verbose_name_plural": "Data Modifications",
            },
        ),
        migrations.CreateModel(
            name="SessionTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("login_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Session Tracker",
                "verbose_name_plural": "Session Trackers",
            },
        ),
        migrations.CreateModel(
            name="SystemAccessTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("resource_accessed", models.CharField(max_length=255)),
                ("is_successful", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Access",
                "verbose_name_plural": "System Accesses",
            },
        ),
        migrations.CreateModel(
            name="TrackingDataRetention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50)),
                ("retention_period", models.IntegerField()),
                ("retention_unit", models.CharField(max_length=10)),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_cleanup", models.DateTimeField(blank=True, null=True)),
                ("next_cleanup", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trackingalert",
            name="triggered_by",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="useractiontracker",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="trackingalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("security", "Security Alert"),
                    ("performance", "Performance Alert"),
                    ("system", "System Alert"),
                    ("compliance", "Compliance Alert"),
                    ("error", "Error Alert"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trackingalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("ignored", "Ignored"),
                    ("false_positive", "False Positive"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useractiontracker",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("page_view", "Page View"),
                    ("button_click", "Button Click"),
                    ("form_submit", "Form Submit"),
                    ("search", "Search Query"),
                    ("filter_apply", "Filter Applied"),
                    ("sort_apply", "Sort Applied"),
                    ("download", "Download"),
                    ("upload", "Upload"),
                    ("purchase", "Purchase"),
                    ("cart_add", "Add to Cart"),
                    ("cart_remove", "Remove from Cart"),
                    ("wishlist_add", "Add to Wishlist"),
                    ("wishlist_remove", "Remove from Wishlist"),
                    ("review_submit", "Review Submitted"),
                    ("profile_update", "Profile Updated"),
                    ("password_change", "Password Changed"),
                    ("email_change", "Email Changed"),
                    ("custom_action", "Custom Action"),
                    ("data_modification", "Data Modification"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="performancemetric",
            index=models.Index(
                fields=["endpoint"], name="store_perfo_endpoin_bef5fd_idx"
            ),
        ),
        migrations.AddField(
            model_name="datamodificationtracker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessiontracker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemaccesstracker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="datamodificationtracker",
            index=models.Index(
                fields=["model_name", "timestamp"],
                name="store_datam_model_n_d7113b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datamodificationtracker",
            index=models.Index(
                fields=["operation_type"], name="store_datam_operati_959cf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiontracker",
            index=models.Index(
                fields=["user", "is_active"], name="store_sessi_user_id_7e5bfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiontracker",
            index=models.Index(
                fields=["login_timestamp"], name="store_sessi_login_t_ab0383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemaccesstracker",
            index=models.Index(
                fields=["access_type", "access_timestamp"],
                name="store_syste_access__8dab9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemaccesstracker",
            index=models.Index(
                fields=["risk_level"], name="store_syste_risk_le_9c1e95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemaccesstracker",
            index=models.Index(
                fields=["is_successful"], name="store_syste_is_succ_ddfaf0_idx"
            ),
        ),
    ]
