# Generated by Django 5.2.10 on 2026-02-01 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(blank=True, max_length=255)),
                (
                    "farm_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Size in acres",
                        max_digits=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                (
                    "primary_crops",
                    models.JSONField(
                        blank=True, default=list, help_text="List of primary crops"
                    ),
                ),
                (
                    "livestock",
                    models.JSONField(
                        blank=True, default=list, help_text="List of livestock"
                    ),
                ),
                ("irrigation_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Farm",
                "verbose_name_plural": "User Farms",
            },
        ),
    ]
