# Generated by Django 5.2.10 on 2026-01-31 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_size",
                    models.DecimalField(
                        decimal_places=2, help_text="Farm size in acres", max_digits=10
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("loamy", "Loamy"),
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("silt", "Silt"),
                            ("peat", "Peat"),
                            ("chalky", "Chalky"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("rainfed", "Rainfed"),
                            ("drip", "Drip"),
                            ("sprinkler", "Sprinkler"),
                            ("canal", "Canal"),
                            ("tube_well", "Tube Well"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_crops",
                    models.JSONField(default=list, help_text="List of crops grown"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
