# Generated by Django 5.2.10 on 2026-01-30 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_performancemetric"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=100)),
                ("commodity", models.CharField(max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("arrival_date", models.DateField()),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-arrival_date"],
                "indexes": [
                    models.Index(
                        fields=["state", "district", "commodity"],
                        name="idx_mandi_loc_comm",
                    ),
                    models.Index(fields=["arrival_date"], name="idx_mandi_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., My Wheat Field", max_length=100),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Village, District, State", max_length=255
                    ),
                ),
                (
                    "size_acres",
                    models.DecimalField(
                        decimal_places=2, help_text="Size in acres", max_digits=6
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("alluvial", "Alluvial Soil"),
                            ("black", "Black Soil"),
                            ("red", "Red Soil"),
                            ("laterite", "Laterite Soil"),
                            ("arid", "Arid/Desert Soil"),
                            ("forest", "Forest Soil"),
                            ("other", "Other"),
                        ],
                        default="alluvial",
                        max_length=50,
                    ),
                ),
                (
                    "irrigation_source",
                    models.CharField(
                        choices=[
                            ("rainfed", "Rainfed"),
                            ("canal", "Canal"),
                            ("well", "Well/Tube Well"),
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                        ],
                        default="rainfed",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "primary_crops",
                    models.ManyToManyField(
                        blank=True, related_name="farms", to="store.crop"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoilHealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_date", models.DateField()),
                (
                    "ph_level",
                    models.DecimalField(
                        decimal_places=2, help_text="pH Value (0-14)", max_digits=4
                    ),
                ),
                (
                    "nitrogen",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nitrogen (N) in kg/ha",
                        max_digits=6,
                    ),
                ),
                (
                    "phosphorus",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Phosphorus (P) in kg/ha",
                        max_digits=6,
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potassium (K) in kg/ha",
                        max_digits=6,
                    ),
                ),
                (
                    "organic_carbon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Organic Carbon %",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Moisture %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Auto-generated or expert recommendations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="soil_recommendations",
                        to="store.product",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_reports",
                        to="store.userfarm",
                    ),
                ),
            ],
            options={
                "ordering": ["-sample_date"],
            },
        ),
        migrations.CreateModel(
            name="CropAdvisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("crop_disease", "Crop Disease"),
                            ("pest_control", "Pest Control"),
                            ("fertilizer", "Fertilizer Use"),
                            ("seeds", "Seeds & Sowing"),
                            ("weather", "Weather Related"),
                            ("general", "General Inquiry"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="advisory/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("answered", "Answered"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Visible to other users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.crop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_advisory_status"),
                    models.Index(fields=["topic"], name="idx_advisory_topic"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "temp_max",
                    models.DecimalField(
                        decimal_places=2, help_text="Max Temperature (C)", max_digits=5
                    ),
                ),
                (
                    "temp_min",
                    models.DecimalField(
                        decimal_places=2, help_text="Min Temperature (C)", max_digits=5
                    ),
                ),
                (
                    "rainfall",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rainfall (mm)",
                        max_digits=6,
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Humidity %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wind Speed (km/h)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Sunny, Cloudy, Rainy, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "forecast_data",
                    models.JSONField(
                        blank=True, help_text="Detailed forecast JSON", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_logs",
                        to="store.userfarm",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("farm", "date")},
            },
        ),
    ]
