# Generated by Django 5.2.10 on 2026-01-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_trackingdataretention_datamodificationtracker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingalert",
            name="triggered_by",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
