# Generated by Django 5.2.10 on 2026-01-18 15:47

from django.db import migrations
from django.contrib.auth.hashers import make_password, identify_hasher

def hash_existing_keys(apps, schema_editor):
    UserAnalyticsAPIKey = apps.get_model('store', 'UserAnalyticsAPIKey')
    for api_key in UserAnalyticsAPIKey.objects.all():
        if api_key.secret_key:
            try:
                identify_hasher(api_key.secret_key)
                # Already hashed, skip
            except ValueError:
                # Not a valid hash, so it's plaintext. Hash it.
                api_key.secret_key = make_password(api_key.secret_key)
                api_key.save()

class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_useranalyticsapikey_secret_key"),
    ]

    operations = [
        migrations.RunPython(hash_existing_keys),
    ]
