# Generated by Django 5.1.4 on 2026-01-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_trackingdataretention_datamodificationtracker_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=50)),
                ("format", models.CharField(max_length=10)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(default=0)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Export",
                "verbose_name_plural": "Tracking Exports",
            },
        ),
    ]
