# Generated by Django 5.2.10 on 2026-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_userfarm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfarm",
            name="farm_size",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Farm size in acres",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="userfarm",
            name="irrigation_type",
            field=models.CharField(
                choices=[
                    ("rainfed", "Rainfed"),
                    ("drip", "Drip"),
                    ("sprinkler", "Sprinkler"),
                    ("canal", "Canal"),
                    ("tube_well", "Tube Well"),
                ],
                default="rainfed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userfarm",
            name="soil_type",
            field=models.CharField(
                choices=[
                    ("loamy", "Loamy"),
                    ("clay", "Clay"),
                    ("sandy", "Sandy"),
                    ("silt", "Silt"),
                    ("peat", "Peat"),
                    ("chalky", "Chalky"),
                ],
                default="loamy",
                max_length=20,
            ),
        ),
    ]
