# Generated by Django 6.0.1 on 2026-01-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_productbatch_journeypoint_productbatch_idx_batch_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("competitor_match", "Competitor Match"),
                            ("stock_based", "Stock Level Based"),
                            ("demand_based", "Demand/Sales Based"),
                            ("time_based", "Time of Day/Week"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g. 10.0) or Fixed Amount",
                        max_digits=10,
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "threshold_stock",
                    models.IntegerField(
                        blank=True, help_text="Stock level to trigger rule", null=True
                    ),
                ),
                (
                    "threshold_sales_velocity",
                    models.IntegerField(
                        blank=True, help_text="Sales per day to trigger", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules run first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
