# Generated by Django 5.2.10 on 2026-01-28 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_trackingdataretention_datamodificationtracker_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per quintal", max_digits=10
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "crop"],
                "indexes": [
                    models.Index(
                        fields=["crop", "market", "date"],
                        name="store_mandi_crop_abbafb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SoilHealthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ph_level",
                    models.DecimalField(
                        decimal_places=2, help_text="pH Level (0-14)", max_digits=4
                    ),
                ),
                (
                    "nitrogen",
                    models.DecimalField(
                        decimal_places=2, help_text="Nitrogen (N) kg/ha", max_digits=5
                    ),
                ),
                (
                    "phosphorus",
                    models.DecimalField(
                        decimal_places=2, help_text="Phosphorus (P) kg/ha", max_digits=5
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        decimal_places=2, help_text="Potassium (K) kg/ha", max_digits=5
                    ),
                ),
                (
                    "organic_carbon",
                    models.DecimalField(
                        decimal_places=2, help_text="Organic Carbon %", max_digits=5
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        blank=True, help_text="AI-generated recommendation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("condition", models.CharField(max_length=100)),
                ("humidity", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["city", "timestamp"], name="store_weath_city_bcf959_idx"
                    )
                ],
            },
        ),
    ]
