# Generated by Django 6.0.1 on 2026-01-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_dynamicpricingrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_date", models.DateField()),
                ("predicted_demand", models.IntegerField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, help_text="0.00 to 1.00", max_digits=5
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "ordering": ["predicted_date"],
                "unique_together": {("product", "predicted_date")},
            },
        ),
    ]
